# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-02 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chris', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(default='', max_length=5)),
                ('acc_no', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=30)),
                ('amount', models.IntegerField(default=0)),
                ('frequency', models.BooleanField(default=True)),
                ('interval', models.IntegerField(default=0)),
                ('mod', models.IntegerField(default=0)),
                ('pay_qty', models.IntegerField(default=0)),
                ('pay_count', models.IntegerField(default=0)),
                ('first_pay', models.DateField(blank=True)),
                ('next_pay', models.DateField(blank=True)),
                ('final_pay', models.DateField(blank=True)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.IntegerField(default=0)),
                ('last_4', models.CharField(default='0000', max_length=4)),
            ],
        ),
    ]
