# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-18 11:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chris', '0003_auto_20190504_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='chris.UserProfile'),
            preserve_default=False,
        ),
    ]
