# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-18 11:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chris', '0004_budget_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chris.UserProfile'),
        ),
    ]
