# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-18 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chris', '0005_auto_20190518_1215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='mod',
            new_name='freq_mod',
        ),
        migrations.AddField(
            model_name='budget',
            name='type',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='budget',
            name='frequency',
            field=models.IntegerField(default=0),
        ),
    ]
