# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-18 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chris', '0007_auto_20190518_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='final_pay',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='budget',
            name='first_pay',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='budget',
            name='next_pay',
            field=models.DateField(blank=True, null=True),
        ),
    ]
