# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-19 20:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chris', '0008_auto_20190518_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='budget',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 19, 20, 29, 2, 248462, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
