# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-20 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chris', '0010_auto_20190519_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='pay_value',
            field=models.IntegerField(default=0),
        ),
    ]
