# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-20 22:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chris', '0012_auto_20190520_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='final_date',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 5, 20, 22, 39, 56, 609425, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
