# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-22 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chris', '0013_auto_20190520_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='pay_ref',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
