# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-24 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chris', '0014_budget_pay_ref'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='status',
            new_name='budget_status',
        ),
        migrations.RenameField(
            model_name='budget',
            old_name='freq_mod',
            new_name='freq_count',
        ),
        migrations.AddField(
            model_name='budget',
            name='pay_status',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
