# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-25 12:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chris', '0015_auto_20190524_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 25, 12, 34, 25, 509259, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
