# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-25 21:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chris', '0016_bank_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='receipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chris.Bank'),
        ),
    ]
