# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-26 12:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chris', '0017_budget_receipient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='receipient',
            new_name='recipient',
        ),
    ]
