# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-26 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chris', '0018_auto_20190526_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='bank',
            field=models.CharField(default='', max_length=10),
        ),
    ]
