# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-26 23:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chris', '0019_auto_20190526_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='fund_amount',
            field=models.IntegerField(null=True),
        ),
    ]
