# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-26 23:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chris', '0020_budget_fund_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='fund_amount',
            new_name='amount_funded',
        ),
    ]
