# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-29 05:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chris', '0022_bank_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='name',
            field=models.CharField(default='', max_length=128),
        ),
    ]
