# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-01 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chris', '0023_bank_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='bank_code',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
