# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-01 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chris', '0025_auto_20190601_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='bank',
            field=models.CharField(default='', max_length=55),
        ),
        migrations.AlterField(
            model_name='bank',
            name='holder_name',
            field=models.CharField(default='', max_length=55),
        ),
    ]
