# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-07 10:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chris', '0026_auto_20190601_1428'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='freq_count',
            new_name='freq_factor',
        ),
        migrations.RenameField(
            model_name='budget',
            old_name='type',
            new_name='mode',
        ),
    ]
