# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-07 10:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chris', '0027_auto_20190807_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='pay_qty',
        ),
    ]
