# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-07 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chris', '0029_budget_pay_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='mode',
            field=models.NullBooleanField(),
        ),
    ]
