# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-10 02:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chris', '0030_auto_20190807_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='recipient_code',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
