# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-10 03:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chris', '0032_auto_20190810_0308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='next_date',
        ),
    ]
