# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-10 03:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chris', '0033_remove_budget_next_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='first_date',
            new_name='next_date',
        ),
    ]
