# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-12 00:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chris', '0034_auto_20190810_0406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='recipient_code',
        ),
        migrations.AddField(
            model_name='budget',
            name='recipient_code',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
